login:
    pattern: /login
    defaults: { _controller: PokouUserBundle:Security:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout

pokou_admin:
    resource: "@PokouAdminBundle/Resources/config/routing.yml"
    prefix:   /

pokou_center:
    resource: "@PokouCenterBundle/Resources/config/routing.yml"
    prefix:   /

