parameters:
#    pokou_admin.example.class: Pokou\AdminBundle\Example

services:
#    pokou_admin.example:
#        class: %pokou_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
