<?php

namespace Pokou\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function listeCategories() {
        $repository = $this->getDoctrine()->getManager()->getRepository('PokouAdminBundle:Categorie');
        $categories = $repository->findAll();
        
        return $categories;
    }
}
