<?php

namespace Pokou\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
    public function listeParametre() {
        $repository = $this->getDoctrine()
                ->getManager()
                ->getRepository('PokouAdminBundle:Configuration');
        $listeParametre = $repository->find(1);
        return $listeParametre;
    }
}
