<?php

namespace Pokou\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PokouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokouRepository extends EntityRepository
{
    public function coefPokou ()
    {
        $repository = $this->getDoctrine()->getManager()->getRepository('PokouAdminBundle:Pokou');
        $coefPokou = $repository->findAll();
        return $coefPokou;
    }
}
