<?php

namespace Pokou\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends EntityRepository
{
    public function listeServices() {
        $repository = $this->getDoctrine()->getManager()->getRepository('PokouAdminBundle:Services');
        $services = $repository->findAll();
        
        return $services;
    }
}
