<?php

namespace Pokou\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvaRepository extends EntityRepository
{
    public function listeTva() {
        $repository = $this->getDoctrine()->getManager()->getRepository('PokouAdminBundle:Tva');
        $listeTva = $repository->findAll();
        return $listeTva;
    }
    
    public function initialisationTaux() {
        
        $taux1 = new Tva();
        $taux1->setTaux(20);
        $a = $this->getDoctrine()->getManager();
        $a->persist($taux1);
        $a->flush();        
        
        $taux2 = new Tva();
        $taux2->setTaux(10);
        $b = $this->getDoctrine()->getManager();
        $b->persist($taux2);
        $b->flush();        
        
        $taux3 = new Tva();
        $taux3->setTaux(5.5);
        $c = $this->getDoctrine()->getManager();
        $c->persist($taux3);
        $c->flush();        
        
        $taux4 = new Tva();
        $taux4->setTaux(2.1);
        $em = $this->getDoctrine()->getManager();
        $em->persist($taux4);
        $em->flush();
        
        $tva = true;
        return $tva;
    }
    
    public function statutTva() {
        $em = $this->getDoctrine()->getManager();
        $config = $em->getRepository('PokouAdminBundle:Configuration')->find(1);
        $tva = $config->getTva();
        return $tva;
    }
}
